package journal

// rebuild.go — Phase 5: deterministic, checksum-verified, restartable rebuild.
//
// Rebuild guarantee:
//   - Deterministic: extents are always processed in sorted (ParityGroupID,
//     LogicalOffset) order so that the same extent is rebuilt on each run.
//   - Checksum-verified: every reconstructed extent byte is verified against
//     the checksum recorded in metadata before writing the rebuilt data to disk.
//   - Restartable: a RebuildProgress record is written to disk after each
//     extent is rebuilt. If the process is interrupted, the next call resumes
//     from the last completed extent ID.
//   - Safe under interruption: an incomplete rebuild leaves previously-rebuilt
//     extents intact; un-rebuilt extents remain on the failed disk (or absent).

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"lukechampine.com/blake3"

	"github.com/xkzy/rdparityd/internal/metadata"
)

// ─── Progress persistence ────────────────────────────────────────────────────

// RebuildProgress records the extent IDs that have been successfully rebuilt.
// It is persisted to disk (binary format, BLAKE3 checksum) after each extent
// is processed so that a restart can skip already-completed work.
//
// On-disk binary layout (big-endian):
//
//	[0:4]   Magic       "RBLD"
//	[4:8]   Count       uint32   number of completed extent IDs
//	[8:16]  Timestamp   int64    UnixNano of last update
//	[16:48] Hash        [32]byte BLAKE3-256 of the payload section
//	[48:]   Payload     count × (uint16 length + bytes)
type RebuildProgress struct {
	DiskID           string    `json:"disk_id"`
	CompletedExtents []string  `json:"completed_extents"`
	LastUpdated      time.Time `json:"last_updated"`
}

const (
	rebuildProgressMagic = "RBLD"
	rebuildProgressHdr   = 48 // magic(4) + count(4) + ts(8) + hash(32)
)

// sanitizeDiskID returns a filename-safe representation of diskID by
// replacing every character that is not alphanumeric, a dash, or an
// underscore with an underscore. This prevents path traversal attacks when
// diskID is used to construct a filesystem path.
func sanitizeDiskID(diskID string) string {
	if diskID == "" {
		return "_"
	}
	out := make([]byte, len(diskID))
	for i := 0; i < len(diskID); i++ {
		c := diskID[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '-' || c == '_' {
			out[i] = c
		} else {
			out[i] = '_'
		}
	}
	return string(out)
}

// progressPath returns the filesystem path for a rebuild progress file.
// diskID is passed through sanitizeDiskID so that arbitrary user input cannot
// cause path traversal or write to unexpected locations.
func progressPath(metadataPath, diskID string) string {
	safe := sanitizeDiskID(diskID)
	return filepath.Join(filepath.Dir(metadataPath), "rebuild-"+safe+".progress")
}

// saveRebuildProgress writes the progress record to disk and fsyncs it.
func saveRebuildProgress(metadataPath string, progress RebuildProgress) error {
	if len(progress.CompletedExtents) > int(^uint32(0)) {
		return fmt.Errorf("rebuild progress count exceeds uint32 format limit")
	}
	for i, id := range progress.CompletedExtents {
		if len([]byte(id)) > 1<<16-1 {
			return fmt.Errorf("completed_extents[%d] too long for rebuild progress encoding: %d bytes > %d", i, len([]byte(id)), 1<<16-1)
		}
	}
	// Encode payload: count × (uint16 len + bytes).
	var payload []byte
	for _, id := range progress.CompletedExtents {
		b := []byte(id)
		lenBuf := make([]byte, 2)
		binary.BigEndian.PutUint16(lenBuf, uint16(len(b)))
		payload = append(payload, lenBuf...)
		payload = append(payload, b...)
	}

	hdr := make([]byte, rebuildProgressHdr)
	copy(hdr[0:4], rebuildProgressMagic)
	binary.BigEndian.PutUint32(hdr[4:8], uint32(len(progress.CompletedExtents)))
	// Store UnixNano as an int64 reinterpreted as uint64 (bit-for-bit identical).
	// All timestamps generated by time.Now() are positive (post-epoch), so
	// the uint64 representation round-trips correctly via int64(binary.BigEndian.Uint64(...)).
	ns := progress.LastUpdated.UnixNano()
	if ns < 0 {
		// Pre-epoch timestamps should never occur in production because
		// LastUpdated is always set to time.Now().UTC() in rebuildDiskFromState.
		// A negative value would indicate a corrupted in-memory struct or a
		// system clock set before 1970 (e.g. RTC battery failure). Clamping
		// to zero is safe because the rebuild progress timestamp is used only
		// for diagnostic/audit purposes and does not affect correctness.
		ns = 0
	}
	binary.BigEndian.PutUint64(hdr[8:16], uint64(ns))
	hash := blake3.Sum256(payload)
	copy(hdr[16:48], hash[:])

	data := append(hdr, payload...)
	path := progressPath(metadataPath, progress.DiskID)
	if err := replaceSyncFile(path, data, 0o600); err != nil {
		return fmt.Errorf("save rebuild progress: %w", err)
	}
	return nil
}

// loadRebuildProgress reads a previously saved progress file. Returns an empty
// RebuildProgress (not an error) when no progress file exists yet.
func loadRebuildProgress(metadataPath, diskID string) (RebuildProgress, error) {
	path := progressPath(metadataPath, diskID)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return RebuildProgress{DiskID: diskID}, nil
		}
		return RebuildProgress{}, fmt.Errorf("read rebuild progress: %w", err)
	}
	if len(data) < rebuildProgressHdr {
		return RebuildProgress{}, fmt.Errorf("rebuild progress file too short")
	}
	if string(data[0:4]) != rebuildProgressMagic {
		return RebuildProgress{}, fmt.Errorf("rebuild progress: invalid magic")
	}
	count := int(binary.BigEndian.Uint32(data[4:8]))
	rawNano := binary.BigEndian.Uint64(data[8:16])
	// Convert back to signed int64 (same bit pattern). Clamp to zero if the
	// stored value exceeds the int64 range (i.e. was originally a negative
	// clamped timestamp); the timestamp is informational only.
	var tsNano int64
	if rawNano <= uint64(1<<63-1) {
		tsNano = int64(rawNano)
	}
	storedHash := data[16:48]
	payload := data[rebuildProgressHdr:]

	computed := blake3.Sum256(payload)
	if !bytes.Equal(computed[:], storedHash) {
		return RebuildProgress{}, fmt.Errorf("rebuild progress: checksum mismatch")
	}

	completed := make([]string, 0, count)
	pos := 0
	for i := 0; i < count; i++ {
		if pos+2 > len(payload) {
			return RebuildProgress{}, fmt.Errorf("rebuild progress: truncated payload")
		}
		l := int(binary.BigEndian.Uint16(payload[pos : pos+2]))
		pos += 2
		if pos+l > len(payload) {
			return RebuildProgress{}, fmt.Errorf("rebuild progress: truncated extent id")
		}
		completed = append(completed, string(payload[pos:pos+l]))
		pos += l
	}

	return RebuildProgress{
		DiskID:           diskID,
		CompletedExtents: completed,
		LastUpdated:      time.Unix(0, tsNano).UTC(),
	}, nil
}

// deleteRebuildProgress removes the progress file after a successful rebuild.
func deleteRebuildProgress(metadataPath, diskID string) {
	_ = removeSync(progressPath(metadataPath, diskID))
}

// ─── Rebuild types ───────────────────────────────────────────────────────────

type RebuildIssue struct {
	ExtentID      string `json:"extent_id,omitempty"`
	ParityGroupID string `json:"parity_group_id,omitempty"`
	Status        string `json:"status"`
	Detail        string `json:"detail,omitempty"`
}

type RebuildResult struct {
	StartedAt        time.Time      `json:"started_at"`
	CompletedAt      time.Time      `json:"completed_at"`
	DiskID           string         `json:"disk_id"`
	Healthy          bool           `json:"healthy"`
	ExtentsScanned   int            `json:"extents_scanned"`
	ExtentsRebuilt   int            `json:"extents_rebuilt"`
	ExtentsSkipped   int            `json:"extents_skipped"`
	FailedCount      int            `json:"failed_count"`
	RebuiltExtentIDs []string       `json:"rebuilt_extent_ids,omitempty"`
	Issues           []RebuildIssue `json:"issues,omitempty"`
	Resumed          bool           `json:"resumed"`
}

type RebuildAllResult struct {
	StartedAt      time.Time       `json:"started_at"`
	CompletedAt    time.Time       `json:"completed_at"`
	Healthy        bool            `json:"healthy"`
	DisksRebuilt   int             `json:"disks_rebuilt"`
	ExtentsRebuilt int             `json:"extents_rebuilt"`
	FailedCount    int             `json:"failed_count"`
	Results        []RebuildResult `json:"results"`
}

// ─── Public API ──────────────────────────────────────────────────────────────

// RebuildDataDisk reconstructs all extents on diskID from parity.
// If a progress file from a previous (interrupted) rebuild exists, it resumes
// from where the last run stopped.
func (c *Coordinator) RebuildDataDisk(diskID string) (RebuildResult, error) {
	return c.RebuildDataDiskContext(context.Background(), diskID)
}

// RebuildDataDiskContext reconstructs all extents on diskID from parity with context support.
func (c *Coordinator) RebuildDataDiskContext(ctx context.Context, diskID string) (RebuildResult, error) {
	lock, err := c.acquireExclusiveOperationLock()
	if err != nil {
		return RebuildResult{}, err
	}
	defer lock.release()
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.rebuildDataDiskContextImpl(ctx, diskID, "")
}

func (c *Coordinator) rebuildDataDiskContextImpl(ctx context.Context, diskID string, failAfter State) (RebuildResult, error) {
	result := RebuildResult{
		StartedAt: time.Now().UTC(),
		DiskID:    strings.TrimSpace(diskID),
		Healthy:   true,
	}
	if c == nil {
		return result, fmt.Errorf("coordinator is nil")
	}
	if result.DiskID == "" {
		return result, fmt.Errorf("disk id is required")
	}
	if err := c.ensureRecoveredLocked("demo"); err != nil {
		return result, err
	}

	state, err := c.loadState(metadata.SampleState{})
	if err != nil {
		return result, fmt.Errorf("load metadata state: %w", err)
	}
	return rebuildDiskFromStateContext(ctx, c.metadataPath, c.journal, state, result, failAfter)
}

func (c *Coordinator) rebuildDataDiskWithRepairFailAfter(diskID string, failAfter State) (RebuildResult, error) {
	return c.rebuildDataDiskContextImpl(context.Background(), diskID, failAfter)
}

// RebuildAllDataDisks reconstructs extents on all data disks that have any
// extents registered in metadata.
func (c *Coordinator) RebuildAllDataDisks() (RebuildAllResult, error) {
	return c.RebuildAllDataDisksContext(context.Background())
}

// RebuildAllDataDisksContext reconstructs extents on all data disks with context support.
func (c *Coordinator) RebuildAllDataDisksContext(ctx context.Context) (RebuildAllResult, error) {
	lock, err := c.acquireExclusiveOperationLock()
	if err != nil {
		return RebuildAllResult{}, err
	}
	defer lock.release()
	c.mu.Lock()
	defer c.mu.Unlock()
	result := RebuildAllResult{
		StartedAt: time.Now().UTC(),
		Healthy:   true,
	}
	if c == nil {
		return result, fmt.Errorf("coordinator is nil")
	}
	if err := c.ensureRecoveredLocked("demo"); err != nil {
		return result, err
	}

	state, err := c.loadState(metadata.SampleState{})
	if err != nil {
		return result, fmt.Errorf("load metadata state: %w", err)
	}

	disks := make([]string, 0)
	seen := make(map[string]bool)
	for _, extent := range state.Extents {
		if extent.DataDiskID == "" || seen[extent.DataDiskID] {
			continue
		}
		seen[extent.DataDiskID] = true
		disks = append(disks, extent.DataDiskID)
	}
	sort.Strings(disks)
	for _, diskID := range disks {
		select {
		case <-ctx.Done():
			result.Healthy = false
			break
		default:
		}
		diskResult, err := rebuildDiskFromStateContext(ctx, c.metadataPath, c.journal, state, RebuildResult{
			StartedAt: time.Now().UTC(),
			DiskID:    diskID,
			Healthy:   true,
		}, "")
		if err != nil {
			return result, err
		}
		result.Results = append(result.Results, diskResult)
		result.ExtentsRebuilt += diskResult.ExtentsRebuilt
		result.FailedCount += diskResult.FailedCount
		if !diskResult.Healthy {
			result.Healthy = false
		}
		if diskResult.ExtentsRebuilt > 0 {
			result.DisksRebuilt++
		}
	}

	result.CompletedAt = time.Now().UTC()
	return result, nil
}

// ─── Internal ────────────────────────────────────────────────────────────────

func rebuildDiskFromState(metadataPath string, journal *Store, state metadata.SampleState, result RebuildResult, failAfter State) (RebuildResult, error) {
	return rebuildDiskFromStateContext(context.Background(), metadataPath, journal, state, result, failAfter)
}

func rebuildDiskFromStateContext(ctx context.Context, metadataPath string, journal *Store, state metadata.SampleState, result RebuildResult, failAfter State) (RebuildResult, error) {
	extents := make([]metadata.Extent, 0)
	for _, extent := range state.Extents {
		if extent.DataDiskID == result.DiskID {
			extents = append(extents, extent)
		}
	}
	if len(extents) == 0 {
		return result, fmt.Errorf("no extents mapped to disk %s", result.DiskID)
	}

	sort.Slice(extents, func(i, j int) bool {
		if extents[i].ParityGroupID == extents[j].ParityGroupID {
			return extents[i].LogicalOffset < extents[j].LogicalOffset
		}
		return extents[i].ParityGroupID < extents[j].ParityGroupID
	})

	// Load any existing progress so we can skip already-rebuilt extents.
	progress, err := loadRebuildProgress(metadataPath, result.DiskID)
	if err != nil {
		// Corrupt progress file: start over rather than silently skipping.
		progress = RebuildProgress{DiskID: result.DiskID}
	}
	if len(progress.CompletedExtents) > 0 {
		result.Resumed = true
	}

	completed := make(map[string]bool, len(progress.CompletedExtents))
	for _, id := range progress.CompletedExtents {
		completed[id] = true
	}

	result.ExtentsScanned = len(extents)
	for _, extent := range extents {
		select {
		case <-ctx.Done():
			result.Issues = append(result.Issues, RebuildIssue{
				ExtentID: extent.ExtentID,
				Status:   "cancelled",
				Detail:   ctx.Err().Error(),
			})
			result.Healthy = false
			break
		default:
		}
		if completed[extent.ExtentID] {
			result.ExtentsSkipped++
			continue
		}

		_, repaired, err := verifyExtent(metadataPath, journal, state, extent, true, failAfter)
		if err != nil {
			result.FailedCount++
			result.Healthy = false
			result.Issues = append(result.Issues, RebuildIssue{
				ExtentID:      extent.ExtentID,
				ParityGroupID: extent.ParityGroupID,
				Status:        "failed",
				Detail:        err.Error(),
			})
			// Do not add to completed; the next run will retry.
			continue
		}

		if repaired {
			// Verify the rebuilt extent matches its stored checksum before
			// recording it as complete. verifyExtent already does this
			// internally but we log it explicitly for audit purposes.
			result.ExtentsRebuilt++
			result.RebuiltExtentIDs = append(result.RebuiltExtentIDs, extent.ExtentID)
			result.Issues = append(result.Issues, RebuildIssue{
				ExtentID:      extent.ExtentID,
				ParityGroupID: extent.ParityGroupID,
				Status:        "rebuilt",
				Detail:        "restored from parity and checksum-verified",
			})
		}

		// Persist progress after each extent so a crash can resume here.
		progress.CompletedExtents = append(progress.CompletedExtents, extent.ExtentID)
		progress.LastUpdated = time.Now().UTC()
		if saveErr := saveRebuildProgress(metadataPath, progress); saveErr != nil {
			// Non-fatal: log and continue. On restart the extent will be
			// re-verified (idempotent).
			result.Issues = append(result.Issues, RebuildIssue{
				ExtentID: extent.ExtentID,
				Status:   "progress-save-failed",
				Detail:   saveErr.Error(),
			})
		}
	}

	result.CompletedAt = time.Now().UTC()

	if result.FailedCount == 0 {
		deleteRebuildProgress(metadataPath, result.DiskID)

		// I8: verify the just-rebuilt disk's extents satisfy E1 (on-disk bytes
		// match stored checksums). The check is scoped to this disk only:
		// a pool-wide CheckIntegrityInvariants call would also examine extents
		// on other disks that may legitimately still be degraded (e.g. during
		// RebuildAllDataDisks where each disk is rebuilt sequentially).
		rootDir := filepath.Dir(metadataPath)
		rebuiltDiskID := result.DiskID
		for _, extent := range state.Extents {
			if extent.DataDiskID != rebuiltDiskID || extent.Checksum == "" {
				continue
			}
			path := filepath.Join(rootDir, extent.PhysicalLocator.RelativePath)
			data, err := os.ReadFile(path)
			if err != nil {
				v := InvariantViolation{
					Code: "E1", Kind: "extent", Entity: extent.ExtentID,
					Message: fmt.Sprintf("cannot read rebuilt extent: %v", err),
				}
				result.Healthy = false
				result.Issues = append(result.Issues, RebuildIssue{
					ExtentID: extent.ExtentID, Status: "post-rebuild-integrity-failed",
					Detail: v.Error(),
				})
				return result, fmt.Errorf("I8: post-rebuild integrity check failed: %w", v)
			}
			normalized := normalizeExtentLength(data, extent.Length)
			if got := digestBytes(normalized); got != extent.Checksum {
				v := InvariantViolation{
					Code: "E1", Kind: "extent", Entity: extent.ExtentID,
					Message: fmt.Sprintf("post-rebuild checksum mismatch: expected=%s got=%s", extent.Checksum, got),
				}
				result.Healthy = false
				result.Issues = append(result.Issues, RebuildIssue{
					ExtentID: extent.ExtentID, Status: "post-rebuild-integrity-failed",
					Detail: v.Error(),
				})
				return result, fmt.Errorf("I8: post-rebuild integrity check failed: %w", v)
			}
		}
	}
	return result, nil
}
